class "opt_video" (CUIWindow)

function opt_video:__init() super()
end

function opt_video:__finalize()

end

function opt_video:InitControls(x, y, xml, handler)

	self:SetWndPos(vector2():set(x,y))
	self:SetWndSize(vector2():set(738,416))
	self:SetAutoDelete(true)

--	self.bk = xml:InitFrame			("frame", self)

	xml:InitStatic					("tab_video:cap_brightness",		self)
	xml:InitTrackBar				("tab_video:track_brightness",		self)

	xml:InitStatic					("tab_video:cap_contrast",			self)
	xml:InitTrackBar				("tab_video:track_contrast",		self)

	xml:InitStatic					("tab_video:cap_gamma",				self)
	xml:InitTrackBar				("tab_video:track_gamma",			self)

	local cap_window_mode			= xml:InitStatic("tab_video:cap_window_mode", self)
	local window_mode				= xml:InitComboBox("tab_video:list_window_mode", self)
	cap_window_mode:Show			(false)
	window_mode:Show				(false)

	xml:InitStatic					("tab_video:cap_resolution",		self)
	local resolution				= xml:InitStatic("tab_video:list_resolution", self)
	resolution:TextControl():SetText(string.format("%dx%d", device().width, device().height))

	xml:InitStatic					("tab_video:cap_ios_profile",		self)
	xml:InitComboBox				("tab_video:list_ios_profile",		self)

	local cap_renderer				= xml:InitStatic("tab_video:cap_renderer", self)
	handler.combo_renderer			= xml:InitComboBox("tab_video:list_renderer",		self)
	handler:Register				(handler.combo_renderer, "combo_renderer")
	cap_renderer:Show				(false)
	handler.combo_renderer:Show		(false)

	-- Disable `combo_renderer` combobox control if `renderer` command locked
	local _enable = true
    if renderer_allow_override ~= nil then
        _enable = renderer_allow_override()
    end
	handler.combo_renderer:Enable(_enable)
end
